version: '3'

services:
  find-a-friend-api-database:
    image: bitnami/postgresql
    container_name: find-a-friend-api-database
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=findafriend